/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.xkerman;

import com.machinepublishers.jbrowserdriver.JBrowserDriver;
import com.machinepublishers.jbrowserdriver.Settings;


public class App {
    public static void main(String[] args) {
        if (args.length < 1) {
            return;
        }
        String url = args[0];
        Settings settings = Settings.builder().headless(false).logJavascript(true).build();
        JBrowserDriver driver = new JBrowserDriver(settings);
        driver.get(url);
    }
}
